version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"       # MongoDB accessible on host LAN
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo_net

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    ports:
      - "8081:8081"        # Mongo Express accessible on host LAN
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
